feat: adds get-public-key functionality to xrp app
Cypherock/sdk pull request #129
Opened 2024-09-30 08:21 UTC by muzaffarbhat07

2024-10-05 10:54 UTC, TejasvOnly requested changes
Missing tests for `create` and `getPublicKeys` operations

2024-10-05 10:54 UTC, TejasvOnly commented on apps/node/src/index.ts
Do not commit this file

2024-10-07 08:23 UTC, muzaffarbhat07 commented on apps/node/src/index.ts
added tests for `getPublicKeys`.
reverted changes from `apps/node/src/index.ts` file
tests for `create` are already added in base

2024-10-08 10:32 UTC, TejasvOnly approved these changes

2024-10-08 10:32 UTC, merged