updated card error handling, proto files and test cases.
Cypherock/sdk pull request #38
Opened 2023-07-10 10:45 UTC by Suraj-Tiwari

2023-07-10 12:50 UTC, irshadCypherock requested changes

2023-07-10 12:54 UTC, irshadCypherock requested changes
We need to map all the sub errors of `CARD_ERROR` as well, so that we can throw it to cysync.

2023-07-10 12:55 UTC, Suraj-Tiwari commented on packages/app-manager/src/operations/authCard/index.ts
> +    // logger.info('Started', params);
yeah we can, but just left it here so can visit it later, this section shouldn't throw any error but it does on desktop which is odd.

2023-07-10 12:58 UTC, irshadCypherock commented on packages/app-manager/src/operations/authCard/index.ts
> +    // logger.info('Started', params);
- Is it tested that this solves the issue on CySync?
- Maybe the error is because the `params` contains callback functions which we are logging?

2023-07-10 18:06 UTC, Suraj-Tiwari commented on packages/app-manager/src/operations/authCard/index.ts
> +    // logger.info('Started', params);
- yes 
- callback will be just treated as a variable, unless logger is doing additional processing, there shouldn't be any issue

2023-07-11 13:02 UTC, irshadCypherock submitted a review, later dismissed

2023-07-11 13:05 UTC, merged