Refactor/evm sign msg
Cypherock/sdk pull request #72
Opened 2023-08-25 14:48 UTC by amanCypherock

2023-09-05 13:00 UTC, irshadCypherock requested changes

2023-09-05 13:00 UTC, irshadCypherock commented on packages/app-evm/src/operations/signMsg/index.ts
>    forceStatusUpdate(SignMsgEvent.CONFIRM);
I think this needs to be at line 68

2023-09-05 13:53 UTC, ujjwal-cyph commented on packages/app-evm/src/operations/signMsg/index.ts
>    forceStatusUpdate(SignMsgEvent.CONFIRM);
updated

2023-09-06 06:43 UTC, irshadCypherock approved these changes

2023-09-06 08:58 UTC, merged